namespace Data
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.42000
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------


    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class books
    {

        private technicalData technicalDataField;

        private writer[] writersListField;

        private publisher[] publishersListField;

        private book[] booksListField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://data.example.com")]
        public technicalData technicalData
        {
            get
            {
                return this.technicalDataField;
            }
            set
            {
                this.technicalDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "http://writer.example.com")]
        [System.Xml.Serialization.XmlArrayItemAttribute("writer", IsNullable = false)]
        public writer[] writersList
        {
            get
            {
                return this.writersListField;
            }
            set
            {
                this.writersListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace = "http://publisher.example.com")]
        [System.Xml.Serialization.XmlArrayItemAttribute("publisher", IsNullable = false)]
        public publisher[] publishersList
        {
            get
            {
                return this.publishersListField;
            }
            set
            {
                this.publishersListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("book", IsNullable = false)]
        public book[] booksList
        {
            get
            {
                return this.booksListField;
            }
            set
            {
                this.booksListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://data.example.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://data.example.com", IsNullable = false)]
    public partial class technicalData
    {

        private student[] authorField;

        private lastModificationDate lastModificationDateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("author")]
        public student[] author
        {
            get
            {
                return this.authorField;
            }
            set
            {
                this.authorField = value;
            }
        }

        /// <remarks/>
        public lastModificationDate lastModificationDate
        {
            get
            {
                return this.lastModificationDateField;
            }
            set
            {
                this.lastModificationDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://data.example.com")]
    [System.Xml.Serialization.XmlRootAttribute("author", Namespace = "http://data.example.com", IsNullable = false)]
    public partial class student : identity
    {

        private string authorIndexNumberField;

        private string authorIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string authorIndexNumber
        {
            get
            {
                return this.authorIndexNumberField;
            }
            set
            {
                this.authorIndexNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string authorID
        {
            get
            {
                return this.authorIDField;
            }
            set
            {
                this.authorIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(student))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://data.example.com")]
    public partial class identity
    {

        private string nameField;

        private string surnameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token")]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://data.example.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://data.example.com", IsNullable = false)]
    public partial class lastModificationDate
    {

        private string lastModificationDayField;

        private string lastModificationMonthField;

        private string lastModificationYearField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "gDay")]
        public string lastModificationDay
        {
            get
            {
                return this.lastModificationDayField;
            }
            set
            {
                this.lastModificationDayField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "gMonth")]
        public string lastModificationMonth
        {
            get
            {
                return this.lastModificationMonthField;
            }
            set
            {
                this.lastModificationMonthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "gYear")]
        public string lastModificationYear
        {
            get
            {
                return this.lastModificationYearField;
            }
            set
            {
                this.lastModificationYearField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://writer.example.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://writer.example.com", IsNullable = false)]
    public partial class writer : identity
    {

        private string writerBirthYearField;

        private string writerIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "gYear")]
        public string writerBirthYear
        {
            get
            {
                return this.writerBirthYearField;
            }
            set
            {
                this.writerBirthYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string writerID
        {
            get
            {
                return this.writerIDField;
            }
            set
            {
                this.writerIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://publisher.example.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://publisher.example.com", IsNullable = false)]
    public partial class publisher
    {

        private string publisherNameField;

        private string publisherIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string publisherName
        {
            get
            {
                return this.publisherNameField;
            }
            set
            {
                this.publisherNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string publisherID
        {
            get
            {
                return this.publisherIDField;
            }
            set
            {
                this.publisherIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class book
    {

        private bookBookWriter bookWriterField;

        private bookBookPublisher bookPublisherField;

        private string bookTitleField;

        private string bookIsbnField;

        private string bookDateOfPublishField;

        private decimal bookPriceField;

        private string bookIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bookBookWriter bookWriter
        {
            get
            {
                return this.bookWriterField;
            }
            set
            {
                this.bookWriterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bookBookPublisher bookPublisher
        {
            get
            {
                return this.bookPublisherField;
            }
            set
            {
                this.bookPublisherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bookTitle
        {
            get
            {
                return this.bookTitleField;
            }
            set
            {
                this.bookTitleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bookIsbn
        {
            get
            {
                return this.bookIsbnField;
            }
            set
            {
                this.bookIsbnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "gYear")]
        public string bookDateOfPublish
        {
            get
            {
                return this.bookDateOfPublishField;
            }
            set
            {
                this.bookDateOfPublishField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal bookPrice
        {
            get
            {
                return this.bookPriceField;
            }
            set
            {
                this.bookPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
        public string bookID
        {
            get
            {
                return this.bookIDField;
            }
            set
            {
                this.bookIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class bookBookWriter
    {

        private string writerIDField = "no id";

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string writerID
        {
            get
            {
                return this.writerIDField;
            }
            set
            {
                this.writerIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class bookBookPublisher
    {

        private string publisherIDField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "IDREF")]
        public string publisherID
        {
            get
            {
                return this.publisherIDField;
            }
            set
            {
                this.publisherIDField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class booksList
    {

        private book[] bookField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("book")]
        public book[] book
        {
            get
            {
                return this.bookField;
            }
            set
            {
                this.bookField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://publisher.example.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://publisher.example.com", IsNullable = false)]
    public partial class publishersList
    {

        private publisher[] publisherField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publisher")]
        public publisher[] publisher
        {
            get
            {
                return this.publisherField;
            }
            set
            {
                this.publisherField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://writer.example.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://writer.example.com", IsNullable = false)]
    public partial class writersList
    {

        private writer[] writerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("writer")]
        public writer[] writer
        {
            get
            {
                return this.writerField;
            }
            set
            {
                this.writerField = value;
            }
        }
    }

}
